scripts/weather.sh
admittedly i can't test this for the use case where it doesn't 429 for at least another 20 something hours
=> Handling the 429 response limit error

README.md, scripts/dracula.sh
=> Add options to disable battery and network

scripts/network.sh
- Use a list of hosts: google.com, github.com, example.com
- Script will try each in turn, stopping at the first one that connects
- Also fix she-bang and some quotes
- Tested with Wifi and Offline.
=> scripts/network.sh: use a list of hosts

scripts/battery.sh, scripts/dracula.sh
Changed it so that battery can be read from BAT1 and BAT0
=> Added powerline symbols

INSTALL.md, scripts/dracula.sh
I think I've did this correct, if I haven't please let me know and I'll be happy to fix this
The way it works is you can set `set -g @dracula-tmux-miiltary true` and it'll set the time in the bottom to military time instead of a 12 hour time. This is my first PR so if I did anything wrong my bad.
=> Adding military time functionality

INSTALL.md, scripts/dracula.sh
PR #24 added the option to change the smiley face into the session name, but it actually was just showing the name of the window, I fixed it and added the option to change it to the window if the user so pleases
=> Fixed 'session' option

scripts/dracula.sh
Fixing an similar issue to #37, but for non-powerline option.
=> Spacing non powerline

INSTALL.md, scripts/cpu_info.sh, scripts/dracula.sh
=> Added CPU functionality, works cleanly with powerline and normal

INSTALL.md, README.md, scripts/dracula.sh, scripts/gpu_usage.sh
=> Adding GPU usage.

scripts/ram_info.sh
=> Fix #53: report MacOS memory correctly

scripts/dracula.sh
A simple if to remove the time option, I do not like it because I already have a huge watch in my desktop environment
=> Option to remove the time

INSTALL.md, README.md, scripts/cpu_info.sh, scripts/dracula.sh, scripts/gpu_usage.sh, scripts/ram_info.sh
I'll take another crack at this tomorrow, this idea just popped in my head and thought I would share, thoughts?
=> Adding ability to change the refresh rate of whole status bar

scripts/ram_info.sh
Hi @danerwilliams I noticed that my old Raspberry Pi were showing RAM usage wrong, and implemented a quick fix to the ram_info script.
=> Added conditional for linux boxes with < 1 GB Ram

scripts/battery.sh, scripts/dracula.sh, scripts/ram_info.sh
I'm submitting this again as just the Battery and Ram, I figured instead of just sitting in a repo stagnant someone could make use of this. CPU usage will eventually be done, time permitting.
Other BSD's support will come eventually.
=> FreeBSD support - Battery and Ram

INSTALL.md
Add missing documentation for time toggle introduced in https://github.com/dracula/tmux/pull/57
=> Document time option toggle

.editorconfig, INSTALL.md, scripts/battery.sh, scripts/cpu_info.sh, scripts/dracula.sh, scripts/gpu_usage.sh, scripts/network.sh, scripts/network_bandwith.sh, scripts/ram_info.sh, scripts/sleep_weather.sh, scripts/utils.sh, scripts/weather.sh
**Changes**
- Consistent formatting across all scripts, add `.editorconfig`
- Resolve #106
- Utils script, share functions across plugins
- Resolve #42
=> Customizations

INSTALL.md, README.md, scripts/dracula.sh, scripts/git.sh
Issue #67 Git status module
This commit will add to the status bar with the git branch of the current repo. If there are outstanding changes the text color is set to red. 
cd into a directory not containing a git repo -> there should be no text just a small empty box 
cd into a directory containing a git repo -> text should be the currently checked out branch 
cd into a directory containing a git repo that is up to date -> text should be dark gray
cd into a directory containing a git repo that is not up to date -> text should be red
=>  Issue #67 Add git functionality

scripts/battery.sh
Pretty simple change to allow setting a custom battery label.
Let me know what I need to do to update docs.
=> Add battery icon option

INSTALL.md, scripts/dracula.sh, scripts/network_ping.sh
I missed a ping plugin so here it is.
=> Ping plugin

README.md, scripts/dracula.sh, scripts/spotify-tui.sh
This pull request added the current spotify playback to the statusbar. The tool spotify-tui must be installed for that.
=> Added the plugin spotify-tui

INSTALL.md, scripts/network_bandwidth.sh
Refactor and add new functionality to network-bandwidth
See #186
=> Update network-bandwidth configuration and documentation

scripts/gpu_usage.sh
Fixing the issue detailed in https://github.com/dracula/tmux/issues/195
=> fix gpu reporting issue #195

scripts/spotify-tui.sh
Add the dracula-spotify-tui-format global variable to specify the display format of the spotify tui extension
=> Add dracula-spotify-tui-format option

README.md, scripts/dracula.sh, scripts/gpu_power.sh, scripts/gpu_ram_info.sh
I have added two plugins for GPU VRAM and power draw.
=> Add plugins for gpu ram and power

scripts/dracula.sh, scripts/terraform.sh
Showing the Terraform workspace you're currently in
=> Added terraform workspace support

scripts/network_bandwidth.sh
if the bc program is missing than the bandwidth shows 0.00
=> check for bc program and show info if not found

scripts/battery.sh
=> UPDATE: the power_supply device selection

scripts/network_vpn.sh
Added network_vpn function for linux(tested on debian)
Showing the IP if tun0 is connected otherwise "NO VPN"
=> Update network_vpn.sh linux

scripts/weather.sh
weather sub-plugin with "error" fallback 
#267
=> Suggested fallback for failing wttr.in weather API

INSTALL.md
Sorry about making 2 PRs, I just realised I forgot to update the doc.
=> Update INSTALL.md for transparent powerline background

scripts/battery.sh
```
$ pmset -g batt | sed -n 2p | cut -d ';' -f 2 | tr -d " " 
charged
```
=> fix full battery on macOS 15

INSTALL.md, README.md, scripts/dracula.sh, scripts/krbtgt.sh
A plugin to display the expiration date of a valid Kerberos ticket granting ticket (TGT).
=> Add krbtgt (Kerberos TGT) plugin

scripts/weather.sh
To fix issue https://github.com/dracula/tmux/issues/318
=> bug fix: temperature not showing for certain weather info

README.md
INSTALL.md file's actual path is ./INSTALL.md .
=> Fix INSTALL.md path in the README.md

README.md, docs/CONFIG.md, scripts/cpu_arch.sh, scripts/dracula.sh, scripts/uptime.sh
Add 2 new plugin `cpu-arch` and `uptime`.
=> Add new plugin cpu-arch and uptime
