scripts/network.sh

This change adds support for network name and status on Linux. It first checks the operating system used, and then runs an appropriate command or commands.
I tested this on Linux 5.5.9 - `5.5.9-arch1-2`. All commands used should be part of a standard Linux install, and the directory `/sys/class/power_supply/BAT0/` should also be standard.

network: add support for linux

---

scripts/battery.sh

This change adds support for battery percentage and status on Linux. It first checks the operating system used, and then runs an appropriate command or commands.
I tested this on Linux 5.5.9 - `5.5.9-arch1-2`. All commands used should be part of a standard Linux install, and the directory `/sys/class/power_supply/BAT0/` should also be standard.

battery: add support for linux

---

README.md
scripts/dracula.sh

Personally, displaying the weather doesn't have a lot of use for me
but additionally I ran into an issue where the API you are using
ratelimited call from my IP address, I guess because it was
overfetching.
This doesn't fix the ratelimited issue, but instead at least gives
people the ability to turn the feature off.
Test Plan:
In `~/.tmux.conf` set the following:
```
set -g @plugin 'tmux-plugins/tpm'
set -g @dracula-show-weather false
set -g @plugin 'camspiers/tmux'
run -b '~/.local/share/tmux/plugins/tpm/tpm'
```
Ensure that weather module no longer loads.
In `~/.tmux.conf` set the following:
```
set -g @plugin 'tmux-plugins/tpm'
set -g @dracula-show-weather true
set -g @plugin 'camspiers/tmux'
run -b '~/.local/share/tmux/plugins/tpm/tpm'
```
Ensure that weather module does stil load.

[Feature] Provides ability to disable weather fetching and display

---

scripts/battery.sh

The original implementation attempted to automatically detect the default battery. Since that technique is error prone (I encountered the same issue), I've removed it in an attempt to resolve #25.
My bash syntax checker also complained about the equality comparison on line 44, so I cleaned that up as well.

Fix Linux implementation of battery.sh

---

scripts/battery.sh
scripts/dracula.sh

rewrote a function in battery.sh to make use of acpi command in linux if it exists or else fallback to /sys/class/power_supply/BAT*
added option to switch powerline separators
added option to switch the smiley face with window name or any other character issue #14

Added option to change the smiley face

---

scripts/network.sh

When using redirection to filter the output of the `iw dev` command (commit b3614321da36c7124f76ecde9aa18a590e684ddb), the return value of the command is affected, so the output will never be **Ethernet**.
Another problem is associated when there is a connection via Ethernet but a wireless adapter is present but not connected, resulting in an empty output.
I fixed this problem by analyzing the filter output instead of the `iw dev` return code. If it is empty, either the Wi-Fi is not connected or there is no adapter present; otherwise, **Ethernet** is displayed.
The use of `printf` is necessary if the SSID starts with dashes (_-_) or with a percent sign (_%_).

Improve wireless detection when interface is down

---

INSTALL.md
scripts/dracula.sh

Since I _almost always_ know which timezone I'm in, I prefer hiding it.
This feature would enable a user to set `@dracula-show-timezone false`.
It defaults to showing the timezone to keep it backward compatible.
Regarding the code:
Setting the timezone to empty is not the most semantic solution.
Yet I felt it was the one where I could prevent rewriting too much of the existing code.
Thanks for this awesome project, it spices up my terminal life!

added option to hide timezone

---

scripts/sleep_weather.sh

If the theme/tmux config is reloaded, a new instance of `sleep_weather.sh` will be spawned without first checking if another instance is already running. This results in unnecessary use of system resources and may cause users to quickly hit their daily API limit. This PR would fix the issue by checking for an existing instance of the script and terminating it if found.
It may be advisable for existing users to run `kill $(pgrep -f 'bash .*/sleep_weather.sh')` and then reload their config to ensure that only one instance is running.
1. Open tmux with the theme enabled
2. Count the number of running processes with `pgrep -af 'bash .*/sleep_weather.sh'`
3. Reload the theme/tmux config (`prefix` + `:source-file ~/.tmux.conf`)
4. Perform step 2 again and compare the output
Output before and …

Prevent multiple instances of sleep_weather.sh from running simultaneously

---

scripts/cpu_info.sh

My locale is set to `nl_NL.UTF-8`, and it uses comma as a decimal separator and breaks the parsing of top output.
This change uses US locale which will generate output with point as a decimal separator.

Specify numeric locale for parsing top output

---

scripts/gpu_usage.sh

Did the following:
1. Support homogeneous-vendor multi-GPU machines. Utilization values are simply averaged.
2. Grepping with `VGA` is more general.
3. Print `GPU unknown` for other GPU vendors.
Tested on my desktop (one NVIDIA GPU, Ubuntu bionic), and my lab server (six NVIDIA GPUs, Ubuntu bionic).

Support multi-gpu environment

---

INSTALL.md
scripts/dracula.sh

This adds a setting to allow changing the date `mm/dd` format on the right status to a `dd/mm` format on as used in countries like the UK. This works in tandem with the military time setting. I've tested only the non-powerline version thanks to terminal limitations but should cover powerline users too.

Add flag for dd/mm date format that works with military time.

---

scripts/weather.sh

It uses [wttr.in](https://github.com/chubin/wttr.in) to get the weather information and the current city based on the IP address
Solves issue #16

add international support for weather module

---

INSTALL.md
scripts/dracula.sh

Enbolden window titles on activity or bell status.  This is more readable, IMO, than the default reverse text, especially when window flags appear in different colors.

47: Enable window flags with `set -g @dracula-show-flags true`.

---

scripts/dracula.sh
scripts/sleep_weather.sh
scripts/weather.sh

Hi!
I added an option to show or not the location in the weather by toggling:
set -g @dracula-show-location false in .tmux.conf to hide it (default true)
I also corrected the temperature that was not cut right if it was minus 0 (-2°C).
The cut for weather_condition as been improve so that it takes everything before the temperature.

Add an option to disable the location information in the weather

---

INSTALL.md

Add missing documentation location information toggle introduced in https://github.com/dracula/tmux/pull/78

Document location information toggle

---

INSTALL.md
scripts/dracula.sh

When using the `dracula-show-left-icon` option with a custom character, there's missing padding to the right of the character like so
To fix this, the extra padding was added when assigning the `left_icon` variable

Added padding at the end of left icon for custom args

---

scripts/battery.sh

Minor fix: removed whitespace before comparing output of battery status.
closes #91

Fix: False AC charging message on MacOS

---

scripts/cpu_info.sh

__Issue__: Closes #97 
__Description__:
Instead of just echo the usage percent (wich have a variable length), `get_percent()` now pass the percent to a normalizer function to set the percent string length always to 5. By doing this the CPU usage status will have a contant length, always placing its valor in the middle of the box.
__Testing__:
I commented the line that gets the percentage of the system in `cpu_info.sh` and set the percentage manually, started a new tmux session without the plugin and manually sourcered `dracula.tmux`. Then, I changed the percentage value to test all valid lengths (from 2 to "1%" to 5 to "11.1%") and waited for the script's sleep to update the status bar.
Obs.: Tested only in linux (debian 10).

Create function to normalize cpu usage width

---

INSTALL.md
README.md
scripts/dracula.sh
scripts/network_bandwith.sh

This feature intend to create a helper to show user network bandwith, without packages dependencies.
I Created a network_bandwith.sh file that's the script helper and I've needed increase the status-right-length value because with the default value the status bar was cutting the bars. Also I've added some installation and readme instructions;
Tested on: `Linux 5.8.0-48-generic Ubuntu 20.10 x86_64 GNU/Linux`.
Made all the changes on the tpm plugin script and run `./dracula.tmux` to load network bandwith script

Network bandwith feature

---

scripts/dracula.sh

This was changed in 8748783 but the main `dracula.sh` script is still looking for it in its old location, which causes tmux to hang.

Correct location of weather data file

---

scripts/dracula.sh

Hi there,
Currently, both the weather and time modules take their color configuration from the `@dracula-weather-colors` option, causing the time module to always look like the weather module :)

Fix incorrect color option being read for the time module

---

scripts/dracula.sh

Hallow all !
Only the most right status element seemed to be padded with a space, for
the non-powerline configuration. The powerline configuration seems to alright 
because the padding is embedded along with the the separator.
This commit moves the padding next to the separator to the script
output instead.

Fix right status spacing

---

scripts/ram_info.sh

Page size on M1 Macs is 16k, this PR updates ram_info script to dynamically fetch the page size.
Let me know if you need me to update this PR, wasn't sure how to contribute.

Fix $used_mem when page size is not 4Kb

---

scripts/dracula.sh
scripts/sleep_weather.sh
scripts/weather.sh

I think I am not alone who is using VPN for their work and weather plugin is showing the location from ipinfo.io, which in case of using VPN gives wrong location.
PR adds support for custom location, just enter your city. You can verify data on http://wttr.in/YOURTOWN
In tmux.conf add:
`set -g @dracula-fixed-location 'Štúrovo'`
PR also resolves issue #34

Enable custom location for weather plugin

---

INSTALL.md
README.md
scripts/cpu_info.sh

This PR adds support for load average to CPU info script.
Also resolves request #118

Add load average support

---

INSTALL.md
scripts/battery.sh

a utils.sh import is missing in battery.sh causing the @dracula-battery-label option to not work

import utils.sh in battery.sh

---

scripts/battery.sh

On Fedora the battery status only match with `Discharging`.

Fix: Battery Status for Fedora 36

---

INSTALL.md
scripts/git.sh

This PR adds a new option to disable untracked files from being reported as local changes. More important, the PR introduces the 
'--no-optional-locks' option. For more info, check the commit message.

git script changes

---

README.md
scripts/dracula.sh
scripts/kubernetes_context.sh

This pull request is adding a plugin for kubernetes. It shows the current kubernetes status in the statusbar. It needs the tool kubectl installed. 
With the variable dracula-kubernetes-context-label the user can add a prefix for the statusbar entry.

Added kubernetes-context plugin

---

scripts/dracula.sh

Resolves an issue cause by a syntax error and a removed executable bit introduced by dracula/tmux#153.
The syntax/permissions issue stops the plugin from running properly when I ran into the issue earlier today.
The missing executable bit is likely what's causing dracula/tmux#178. It basically implements the fix @ramaskez [suggested](https://github.com/dracula/tmux/issues/178#issuecomment-1305988132).

fix(dracula.sh): fix execution errors

---

INSTALL.md
scripts/dracula.sh
scripts/git.sh

With this new option, we get information about which remote branch we're tracking. On top of this, we'll get information about ahead/behind commits when we diverged from remote. The output format will be in the form:
'local...remote +ahead -behind',
where ahead and behind are the number of commits ahead and behind.
This functionality is controlled by a new option called '@dracula-git-show-remote-status'.
Note that for this to be properly displayed, we need to increase the size of the right status bar when the git plugin is enabled.
In order to be easier to introduce the change, getMessage() was also a bit changed in order to be easier to append the remote info.
This is how this looks like:

git: add remote info support

---

scripts/ram_info.sh

View issue #165 
- `free` show "Mem" every time on col 2 (hard-coded https://gitlab.com/procps-ng/procps/-/blob/master/src/free.c#L382)
- Remove useless comparison and duplicate call to `free`

🐛 fix(#165): is no longer based on word matching

---

scripts/dracula.sh

This PR adds the option to hide any plugin with an empty output. This allows the creation of alert plugins that are hidden in most cases.
Examples:
- #161 with and without additional clients attached:
Before this PR with no clients:
- The battery percent could be configured to show only under a certain percentage, and the CPU and RAM could optionally be hidden under a certain threshold

Add option to show/hide plugins with empty output

---

scripts/cpu_info.sh

Change to display the defined "dracula-cpu-usage-label" value (e.g. CPU) when load average instead percentage.
Currently the lable is not displayed if CPU load average is

Display CPU label on CPU load configuration

---

scripts/cwd.sh

I noticed that the cwd plugin fails with directory names that have spaces. Upon realizing this I want to fix my previous contribution. I pulled the function directly from the 'git' plugin but the for loop broke up multi-word directory names.
Previous:
After changes:

fix bug with multi-word cwd

---

INSTALL.md
README.md
scripts/dracula.sh
scripts/tmux_ram_info.sh

This shows the total RAM usage of the tmux server and all child processes. ~~Requires `pstree`~~.
Example (in purple):

Add tmux-ram-usage plugin

---

INSTALL.md
scripts/dracula.sh
scripts/hg.sh

I added support for tracking mercurial repositories similar to the existing git repository support.
```
set -g @dracula-plugins "hg time"
```
Clean repository
Dirty repository
Tested each configuration:
```
set -g @dracula-hg-disable-status true
set -g @dracula-hg-show-diff-symbol "^"
```
```
set -g @dracula-hg-no-untracked-files true
```
```
set -g @dracula-hg-no-repo-message "no-hg"
```
```
set -g @dracula-hg-show-current-symbol "@"
```

Add mercurial script

---

INSTALL.md
README.md
scripts/continuum.sh
scripts/dracula.sh

This PR shows the status of the latest [tmux-continuum](https://github.com/tmux-plugins/tmux-continuum) save and a countdown to the next save.
If no save is present:
When a save occurs:
Then the timer resets:

Add tmux-continuum status plugin

---

scripts/dracula.sh

I saw this has been discussed before, and rejected for bloat. This simply adds another configuration to the left icon to make it more useful than the default smiley face. 
The primary motivation for this is I have multiple boxes I tmux to, and I'd like to use the dracula theme everywhere and still be able to distinguish between which box I'm connected to.

Add hostname option for show_left_icon

---

scripts/network.sh

My SSID is `^_^`. I noticed that gets cutt of to `_^` in the status bar. 
I think the original regex (introduced here: https://github.com/dracula/tmux/pull/39) is just wrong, maybe the "start of line" indicator is in the wrong place? Anyway, this new regex will fix that.
The plain SSID without the regex replacement:
```
❯ echo "$(/System/Library/PrivateFrameworks/Apple80211.framework/Resources/airport -I | grep -E ' SSID' | cut -d ':' -f 2)"
^_^
```
(note the extra space it's supposed to remove)
Before:
```
❯ echo "$(/System/Library/PrivateFrameworks/Apple80211.framework/Resources/airport -I | grep -E ' SSID' | cut -d ':' -f 2)" | sed 's/ ^*//g'
_^
```
After: 
```
❯ echo "$(/System/Library/PrivateFrameworks/Apple80211.framework/Resources/airport -I | grep -E ' SSID' | cut -d ':' -f 2)" | …
```

Update network.sh to not cut off SSIDs starting with `^`

---

INSTALL.md
README.md
scripts/dracula.sh
scripts/mpc.sh

- feat: Added mpc plugin
- feat: Added MPC documentation
- feat: Added tmux.conf customizations
Introduces a MPC Plugin for this theme.
Closes #238.
PR introduces a mpc plugin, which can be enabled by the user using the `mpc` keyword in the `@dracula-plugins` variable.
This plugin shows the current state of MPD in the tabline.
The plugin supports the plugin customizations including
- Colors (@dracula-mpc-colors)
- Display Format (@dracula-mpc-format). The reference for which is [here](https://www.musicpd.org/doc/mpc/html/).
For the above functionality. 2 files have been edited
- `scripts/mpc.sh`
- `scripts/dracula.sh`
This plugin requires the `mpc` tool to be installed.
All of the above info is also updated in
- `README.md`
- `INSTALL.md`
Both the customizations have been tested on my …

MPD Plugin

---

INSTALL.md
README.md
scripts/dracula.sh
scripts/ssh_session.sh

This plugin shows ssh connection information of active TMUX pane in the status line.
The default format is:
`user@hostname`
It can be configured to show also the connection port via `@dracula-show-ssh-session-port true`
`user@hostname:port`
When no ssh session is active it will show current user and hostname of local machine i.e: `whoami@hostname`
Color can be configured as any other dracula plugin. Default background is green and foregraund dark_gray.
Useful when user@hostname is not present in the terminal prompt or if working inside a terminal application e.g; vim, htop, etc.
Plugin appearence:

Add ssh-session plugin

---

scripts/ram_info.sh

The system_profiler command used to determine the total memory on darwin systems performs an "Activation Lock" check. This can produce a delay in returning total memory. I began experiencing delays of around 10 seconds.
Switching from system_profiler to sysctl to calculate total memory bypasses the "Activation Lock" check / timeout scenario.
Results of "time" command using system_profiler:
> system_profiler SPHardwareDataType  0.17s user 0.23s system 3% cpu 10.165 total grep -a "Memory:"  0.00s user 0.00s system 0% cpu 10.164 total awk '{print $2 $3}'  0.00s user 0.00s system 0% cpu 10.163 total
Results of "time" command using sysctl:
> sysctl -n hw.memsize  0.00s user 0.00s system 83% cpu 0.004 total awk '{print $0/1024/1024/1024 " GB"}'  0.00s user 0.00s system 86% cpu 0.004 total

Fix: Avoid potential delay in calc of RAM (darwin)

---

scripts/dracula.sh
scripts/weather.sh
scripts/weather_wrapper.sh

If you set the @dracula-fixed-location to "San Diego, California" it ends up looking at "San" which is somewhere in South Korea. This occurs for any fixed-location that has a space. Something like "Portland, Oregon" can be modified to "Portland,Oregon" and still work but we can't remove the space from "San Diego". The reason that spaces in the fixed location break the backend request is that dracula.sh loses everything after the space.
Q: Why does the fixed-location end up as "San"?
A: In dracula.sh the fixed-location is not wrapped in quotes when embedded in the status-right string.
A: In weather_wrapper.sh the call to weather.sh does not wrap the fixed-location argument with quotes.
Q: When these are fixed why do we get a broken link? A: Since we are calling a web service using a url, …

Fix multi word fixed location

---

scripts/network_bandwidth.sh

So I went to enable network-bandwidth (on a mac) and noticed this wasn't supported yet, but it was only *after* getting some custom changes working locally that I even thought to check if there was already a PR for it haha.
I see #113 exists already, but it looks like the person who made that PR just got busy with work and hasn't had time to address all the feedback and resolve the conflicts, and progress seems to have stalled on that several years ago - so I really hope I'm not stepping on any toes by making a separate PR for the same feature, but I'd really love to get this merged into the repo so that I don't need to run a modified version of this repo and manually keep it in sync with my local changes when I update to newer versions.
please let me know if there's anything I should …

add network bandwidth support for macOS

---

INSTALL.md
README.md
scripts/dracula.sh
scripts/playerctl.sh

Added a plugin for the playerctl cli tool.
https://github.com/altdesktop/playerctl
This tool can control multiple media players, I just implemented the `playerctl metadata` command with a configurable format.
https://github.com/altdesktop/playerctl#printing-properties-and-metadata

feat: Added playerctl plugin

---

scripts/network.sh

The `airport` command is now deprecated on macOS 14.4+. Changing it to use the `networksetup` command to get this information instead based on suggestions in #256.

Change how Wi-Fi network info is received on Mac

---

scripts/ram_info.sh

This PR addresses the incorrect RAM usage calculation for MacOS in `ram_info.sh`. Previously, the calculation for `used_mem` only took into account the `active` and `wired` memory. This leaves out key components of used memory, leading to potentially inaccurate results.
Changes in this PR involve modifying the calculation to include `compressor` and `speculative` memory. This change yields a more complete calculation of used memory.

Fix MacOS RAM usage calculation in ram_info.sh

---

scripts/gpu_power.sh
scripts/gpu_ram_info.sh
scripts/gpu_usage.sh

i myself and other people have had issues with lspci not being available or not returning the right values for data to be displayed, despite there being an nvidia gpu and functioning nvidia-smi. this commit adds an optional flag that allows to tell tmux that there is an nvidia gpu, without any checks.
just `set -g @dracula-ignore-lspci true` and it works. this is partially in response to #272

allow user to force getting gpu info without asking lspci #272

---

README.md
scripts/dracula.sh
scripts/libre.sh

I was recently diagnosed with Type 2 Diabetes, and I wanted a way to keep a close eye on my blood glucose levels while working. Since I am an avid user of tmux and have been using the dracula-tmux theme for a while, I thought it would be a great idea to integrate a script that displays my glucose levels directly in tmux. This script helps me manage my diabetes more effectively by keeping this vital information always visible.
- Fetches glucose data from the LibreView API
- Caches data to minimize the number of API requests
- Displays the latest glucose level along with a trend indicator in the tmux status bar
- Manages log files by rotating them when they exceed a specified size
1. The script loads configuration settings from `~/.tmuxlibre.conf`.
2. If the configuration file does not …

feat: Added plugin to show CGM data from libeview api

---

README.md
scripts/battery.sh

in reference to #225 this pull request implements nerdfont icons as battery indicators. it shows how much and whether the pc is charging. additionally the pull request is adding a few extra cases i stumbled upon in macos.
please let me know if my change to the readme is sensible or should be altered to not break the pattern.
special thanks to @sydrawat01 whose code i partially copied to replace my old solution with.

feature/ better battery indication

---

README.md
scripts/spotify-tui.sh

in reference to issue #192 this adds a flag to set the maximum length that spotify is allowed to display.
additionally this fixes there being weird output when spt signals that no device is available.
in #192 it is mentioned that kubernetes has a similar issue, so i think that this solution could likely be used there too, but i dont use kubernetes, so i cant test it.

feature/ add max len to spotify and fix output when no device available

---

scripts/battery.sh

fix show battery percent sign on linux

---

scripts/battery.sh

Follow-up to https://github.com/dracula/tmux/pull/276.
However, the icons for charging from AC have been replaced with a single-symbol icon instead of two symbols for better visibility.

better battery indication for charging from AC

---

scripts/weather.sh

My work environment blocks outgoing ping so the weather applet has never worked. 
I've changed the weather script to use Linux's TCP stack to test connection to port 443 of ipinfo.io instead of pings.
I also added a space for formatting the Unicode symbol and the temperature as on my system they were overlapping, I am happy to revert that change if requested.

fixed weather app showing "Location Unavailable"

---

scripts/ssh_session.sh

adding an option that allows to hide the ssh host when not connected via ssh.
so far i found it confusing when my laptops host was displayed in the ssh_session flag. this PR adds an option (that per default is deactivated) to hide the flag when not connected via ssh.
documentation follows in #278

feature/hide ssh-session when not conntected

---

scripts/weather.sh

This is a follow on to my previous request that changed how status was checked for the weather sites. This edit is still using BASH's builtin TCP connections for testing. Added the timeout command so that the status bar doesn't have "NOT READY". Also added a check for 'wttr.in' port 443 as that site is used to get the actual weather information.
I also changed the displayed message when either site is unavailable from "Location Unavailable" to "Weather Unavailable" as it could be either 'wttr.in' or 'ipinfo.io' that is down and causing the error.

weather.sh: added timeouts & checking for 'wttr.in'

---

scripts/playerctl.sh

Updated playerctl script with a scrolling text based on the character number returned from the `playerctl_playback` variable. Right now the length is hard coded to be 25 but could be extended by updating the api for media controls.

Updated playerctl script to allow scrolling text

---

scripts/network_bandwidth.sh

Use fixed width for network bandwidth to avoid jumps.

Use fixed width for network bandwidth to avoid jumps

---

scripts/dracula.sh

When `$show_day_month` is false, but `$show_military` is true, we can render a clock with date information.
Previously, `$show_day_month` had no effect on the output.

Difference between !$show_day_month and $show_military (show clock only)

---

scripts/weather.sh

`timeout` command is not available in bash on OSX by default. This PR checks weather the OS is OSX and creates a `timeout` function emulating the timeout behaviour.

fix: emulate timeout command for OSX

---

scripts/battery.sh

It is possible that $BAT contains multiple power_supplies like
```bash
/sys/class/power_supply/AC
/sys/class/power_supply/BAT0
/sys/class/power_supply/ucsi-source-psy-USBC000:001
```
In such a case, the original code becomes
`cat AC BAT0 ucsi-source-psy-USBC000:001/status` (path prefix omitted). It fails to run because you cannot `cat` a directory.

Fix: get status and capacity with multiple power_supplies

---

README.md
scripts/battery.sh

If tmux theme is run on a desktop the battery space is empty.
Restore the previous behavior displaying AC and an icon.

Add icon for AC mode

---

scripts/dracula.sh

I've tried to create the least possible if statements to achieve this. This should solve #101 
I've added the 2 following options:
1. @dracula-transparent-powerline-bg -> Default to false, set background transparency on the powerline
2. @dracula-inverse-divider -> I had to change the divider for the window panes because I couldn't get the foreground color to be transparent, only the backgroud. So I've set this inversed divider to be used if *transparent-powerline-bg* is set to *true*. I've added it to the options so the user could use another divider if he had decided to change the *show-left-sep*
I've added some new variables :
1. bg_color -> set the backgroud color
2. window_sep_fg -> set the foreground color of the windows separator (it is necessary to change it if we use the inversed …

Add transparent background to the powerline

---

scripts/network.sh

Since Apple apparently has changed it's functionality

Patch to fix #290

---

scripts/network.sh

There air wifi networks that are not compatible with AirPort. In such a case the network.sh script does not detect correctly the SSID.
The message reported is:
"You are not associated with an AirPort network."
Fix the script detecting correctly the SSID of networks that do not support AirPort.

mac: Fix network detection

---

scripts/weather.sh
scripts/weather_wrapper.sh

wttr.in occasionally has issues where requests hang, this can cause issues in the status bar.
changed the script so it exports defined functions and calls them in a sub-shell. This allows for use of the timeout command on bash functions.

weather.sh: added timeouts to curl requests

---

scripts/weather.sh
scripts/weather_wrapper.sh

The weather plugin:
- On Mac: reports empty results because the default bash is stack to version 3 and seems not cooping with the changes reverted
- On Linux: it work but reports the wrong location
Propose to revert the changes to make it working again.

The weather plugin is broken: revert the latest changes to make it functional again

---

README.md
scripts/dracula.sh
scripts/sys_temp.sh

* Complements #149
* Use `lm-sensors` package to read temperature
* Detect Raspberry Pi and keep using vcgencmd in case.

add: Generic system temperature support

---

scripts/weather.sh

Due to problems in `"°" | rev` when using the US UTF-8 Locale

update locale of weather.sh to utf8

---

scripts/playerctl.sh

the playerctl plugin is outputting a lot of white space when nothing is running.
this pr aims to fix that and kill any output if nothing is running.
in reference to #312 
i would like @joncvn from that issue to review this pr properly, as i wasnt able to do that right now

check whether output is empty and exit before entering scrolling output

---

docs/color_theming/README.md
docs/color_theming/tomorrow_night.md

As referenced in issue #312, I am proposing a new colorscheme into the doc, the [tomorrow-theme](https://github.com/chriskempson/tomorrow-theme/tree/master)
Here is below few screenshots of each theme applied for tmux:

add tommorow night color scheme

---

INSTALL.md
README.md
scripts/dracula.sh
scripts/network-public-ip.sh

This plugin shows public IP at TMUX status line.
Color is configurable. Default foreground: cyan and background: dark_gray (inherits existing network plugin color scheme).
Label is configurable. Default empty string.  
Sample of plugin working. IP masked for privacy sake.

add network public ip plugin

---

scripts/weather.sh

When wttr.in reaches call limit returns the following:
Sorry, we are running out of queries to the weather service at the moment. Here is the weather report for the default city (just to show you what it looks like). We will get new queries as soon as possible.
You can follow https://twitter.com/igor_chubin for the updates.
Which makes weather.sh display a random error.
Make the error predictable.

weather.sh: Introduce fallback when wttr.in reaches call limit

---

scripts/kubernetes_context.sh

- Correctly parses ARNs from EKS clusters within a govcloud AWS tenant (example: `arn:aws-us-gov:eks:us-gov-west-1`)

feat(kubernetes-context): Support AWS govcloud accounts

---

scripts/dracula.sh

This fixes a bug on the `@dracula-kubernetes-context-label` option in `kubernetes_context` plugin.
`kubernetes_context.sh` is called with positional args as such:
```
kubernetes_context.sh $eks_hide_arn $eks_extract_account $hide_kubernetes_user $show_only_kubernetes_context $show_kubernetes_context_label
```
When `show_only_kubernetes_context` defaults to "", arg $5 `show_kubernetes_context_label`,  becomes arg $4 `show_only_kubernetes_context`. Effectively, the value of `@dracula-kubernetes-context-label` is passed to the script as `show_only_kubernetes_context` instead of `show_kubernetes_context_label` So the default value for `show_only_kubernetes_context` needs to be a non-zero string.
Here are screenshots showing the bug:
`@dracula-kubernetes-context-label` has no effect when …

Default show_only_kubernetes_context to false

---

scripts/weather.sh
scripts/weather_wrapper.sh

No issue submitted yet.
Fix Darwin timeout function duration argument. Remove unnecessary API calls to “ipinfo.io”. Confirm to Google Shell style guide and appease shellcheck.
The Darwin [timeout function](https://github.com/dracula/tmux/tree/dd1a7ab5a6e462a26723f63f968d79a4c2081510) makes use of variable `duration` which does not exist.
One execution of the `./scripts/weather.sh` makes 4 remote API calls, 2 calls to the weather service endpoint [wttr.in](https://wttr.in) and 2 calls to the geodata endpoint [ipinfo.io](https://ipinfo.io) to fetch city and region. We should make use of the first weather call for both error checking and data gathering. The calls to the geodata endpoint are not necessary as the weather endpoint provides this functionality. This change results in a single API …

refactor(weather): Fix timeout, reduce calls, apply shellcheck

---

scripts/cwd.sh

in reference to #324 this pr attempts to implement the suggestion.
tested on macos
not yet documented.
use `set -g @dracula-cwd-length "0"` to set the max length, where 0 is unrestricted.
whenever the paths length is cut, it is displayed without / or ~/ to the left of it to prevent confusion.
example:
max length is 1:
/ becomes / as usual
/Users becomes /Users as usual
/Users/username becomes ~ as usual
/Users/username/.config becomes ~/.config as usual
/Users/username/.config/tmux becomes tmux. no / to the left indicates a cut path
max length is 3:
/Users/username/.config becomes ~/.config as usual
/Users/username/.config/tmux/plugins becomes ~/.config/tmux/plugins as usual
/Users/username/.config/tmux/plugins/tmux becomes tmux. no / to the left indicates a cut path
max length is 0: …

feature: add max length feature to cwd

---

scripts/network_vpn.sh

on macos and linux the vpn option now is able to show the name of the vpn if in verbose mode or `VPN` if verbose is off.
if a tailscale exit-node is used, it shows its name in verbose, or `Tailscale` if verbose is off.
scutil did some funky stuff for me, so i had to filter out the asterisks 😅
new options for the network-vpn plugin
`@dracula-network-vpn-label` 
this option is what is displayed when verbose is false.
if verbose is true, this label is the prefix to the name of the vpn/ exitnode.
`@dracula-network-vpn-verbose`
whether to display the vpn/ exitnode name

feature/ MacOS show vpn name and tailscale exit node if active

---

scripts/dracula.sh

The loop parsing plugins skips over sys-temp due to a slight misplacement.

fix sys-temp being ignored

---

.github/workflows/check-syntax.yml

ubuntu-20.04 was deprecated and removed from use on 20250415. Updating to latest prevents us from having this issue in the future. As this is a pretty low-consequence test, I feel comfortable using the latest version here.

gha: ubuntu-20.04 -> ubuntu-latest

---

scripts/network-public-ip.sh
scripts/weather_wrapper.sh

Apply caching to the public IP just like the weather plugin, to prevent curl every few seconds.

Cache ip address in network-public-ip plugin

---

scripts/cpu_info.sh

Grepping the output of top for `Cpu(s)` includes a row for the `grep "Cpu(s)"` process, which sometimes ends up being selected by `tail -1`, causing a nonsensical %CPU reading (in orange in the screenshot below).
This fix uses the pattern `[C]pu(s)` to exclude the search pattern in the grep process itself, a la this stackexchange https://unix.stackexchange.com/a/74186.
It is still possible for the grep pattern to match `Cpu(s)` in the arguments for another process, but that seems much less likely.

Fix cpu_info bug

---

scripts/tmux_ram_info.sh

Occurs with lines too long that get truncated, causing unclosed parentheses and breaking the sed regex, leading to an empty output. The `-l` option fixes this.
The `-T` option is for removing unnecessary PIDs (thread PIDs) from pstree output and may remove the duplicate PIDs seen in #321.
May fix #321

Fix tmux_ram_info bug

---

scripts/gpu_power.sh
scripts/gpu_ram_info.sh
scripts/gpu_usage.sh

Changes unknown outputs by `scripts/gpu_*` to be the correct output for 1 or more AMD/Intel GPUs
`GPU 0%|0%  VRAM 34MB/4.0GB|1.2GB/8.0GB  GPUP 1/43W|16/156W`

Adding GPU Use/mem/power for AMD & Intel GPUs

---

docs/CONFIG.md
scripts/dracula.sh
scripts/mac-player.sh

Sorry for the delay, this is based on the enhancment pull request #336 
The following things were done based on the tasks assigned to myself:
- Tidal - not natively supported for applescript
- Firefox ( not applescript supported )
- Chromium and Firefox variants (arc, zed) - (not applescript supported)
Contains a remote feature but the apps only supported are:
- spotify
- music (apple music)

Mac player
